add_newline=true
command_timeout=3000 #ms

right_format = "$kubernetes $gcloud"

[kubernetes]
format = '[$symbol$context( \($namespace\))](dimmed $style)'

[gcloud]
symbol = ""
format = 'gcloud [$symbol$account(@$domain)(\($region\)):(\($project\))]($style) '

[aws]
disabled = true

[battery]
full_symbol = "🔋 "
charging_symbol = "🔌 "
discharging_symbol = "⚡ "

[[battery.display]]
threshold = 20
style = 'bold red'

[character]
format = "❯❯ "
success_symbol = "❯❯(bold green) "
error_symbol = "❯❯(bold red) "

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_status]
disabled = true

[hostname]
ssh_only = true
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = false

[time]
time_format = "%H:%M"
format = "$time($style) "
style = "bright-white"
disabled = true

[username]
style_user = "bold dimmed blue"
show_always = true

[git_branch]
format = " [$symbol$branch]($style) "
symbol = " "
style = "bold yellow"

[rust]
symbol = " "

[python]
symbol = " "

[nodejs]
symbol = " "

[docker_context]
symbol = " "